FROM docker.io/library/golang:1.25.3 AS builder

ARG CADDY_TAG="v2.10.2"
ARG XCADDY_TAG="v0.4.5"
ARG CADDY_DIST_CHECKSUM="6e9d3ed576e49c9159057a71f32d236f4127f9b53a1f697631b8a0430e3e20ce"
ARG XCADDY_CHECKSUM="53c6a9e29965aaf19210ac6470935537040e782101057a199098feb33c2674f8"

ENV CGO_ENABLED=0

RUN curl -L -o dist.tar.gz https://github.com/caddyserver/dist/archive/refs/tags/${CADDY_TAG}.tar.gz \
    && curl -L -o xcaddy.tar.gz https://github.com/caddyserver/xcaddy/archive/refs/tags/${XCADDY_TAG}.tar.gz \
    && printf "%s dist.tar.gz" "${CADDY_DIST_CHECKSUM}" | sha256sum -c - \
    && printf "%s xcaddy.tar.gz" "${XCADDY_CHECKSUM}" | sha256sum -c - \
    && mkdir -p xcaddy dist \
    && tar --strip-components=1 -C xcaddy -xzf xcaddy.tar.gz \
    && tar --strip-components=1 -C dist -xzf dist.tar.gz \
    && rm xcaddy.tar.gz dist.tar.gz \
    && cd xcaddy \
    && go run cmd/xcaddy/main.go build ${CADDY_TAG} \
        --with github.com/caddy-dns/cloudflare \
        --with github.com/sagikazarmark/caddy-fs-s3 \
        --output /usr/bin/caddy

FROM cgr.dev/chainguard/wolfi-base:latest

ARG CADDY_TAG

RUN apk add --no-cache \
    ca-certificates \
    libcap \
    mailcap

RUN mkdir -p \
        /config/caddy \
        /data/caddy \
        /etc/caddy \
        /usr/share/caddy

ENV CADDY_VERSION=${CADDY_TAG}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY --from=builder /go/dist/config/Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /go/dist/welcome/index.html /usr/share/caddy/index.html

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data

LABEL org.opencontainers.image.version=${CADDY_TAG}
LABEL org.opencontainers.image.title=Caddy
LABEL org.opencontainers.image.description="a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go"
LABEL org.opencontainers.image.url=https://caddyserver.com
LABEL org.opencontainers.image.documentation=https://caddyserver.com/docs
LABEL org.opencontainers.image.vendor="Caleb Xu"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.source="https://github.com/alebcay/container-images"

EXPOSE 80
EXPOSE 443
EXPOSE 443/udp
EXPOSE 2019

WORKDIR /srv

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
