FROM docker.io/library/golang:1.25.4 AS builder

ARG RCLONE_TAG="v1.72.1"
ARG RCLONE_DIST_CHECKSUM="322c73932b533571880832c0e07abdf9492c7f329b7d1dcdbd2a195fa2635a77"

ENV CGO_ENABLED=0

RUN curl -L -o dist.tar.gz https://github.com/rclone/rclone/archive/refs/tags/${RCLONE_TAG}.tar.gz \
    && printf "%s dist.tar.gz" "${RCLONE_DIST_CHECKSUM}" | sha256sum -c - \
    && mkdir -p rclone \
    && tar --strip-components=1 -C rclone -xzf dist.tar.gz \
    && rm dist.tar.gz \
    && cd rclone \
    && go build -ldflags="-s -w -X github.com/rclone/rclone/fs.Version=$(cat VERSION)" -o /usr/bin/rclone

FROM cgr.dev/chainguard/wolfi-base:latest

COPY --from=builder /usr/bin/rclone /usr/bin/rclone
COPY sync.sh /sync.sh
COPY rclone.conf.in /rclone.conf.in
COPY stats.html.in /stats.html.in

RUN apk add --no-cache \
        ca-certificates \
        fuse3 \
        tzdata \
    && echo "user_allow_other" >> /etc/fuse.conf \
    && addgroup -g 1009 rclone \
    && adduser -u 1009 -Ds /bin/sh -G rclone rclone \
    && chmod 555 /sync.sh \
    && chmod 444 /rclone.conf.in /stats.html.in

ENTRYPOINT [ "/sync.sh" ]

WORKDIR /data
ENV XDG_CONFIG_HOME=/config
