#!/bin/sh
set -o errexit

chmodf() { find "$2" -type f -exec chmod -v "$1" {} \;
}
chmodd() { find "$2" -type d -exec chmod -v "$1" {} \;
}

printf "\n========================================================\n"
# If DataDirectory, identity keys or torrc is mounted here,
# ownership needs to be changed to the TOR_USER user
chown -Rv "${TOR_USER}":"${TOR_USER}" /var/lib/tor
# fix permissions
chmodd 700 /var/lib/tor
chmodf 600 /var/lib/tor

if [ ! -e /tor-config-done ]; then
    touch /tor-config-done   # only run this once

    # Add Nickname from env variable or randomized, if none has been set
    if ! grep -q '^Nickname ' /etc/tor/torrc; then
        if [ "${TOR_NICKNAME}" = "Tor4" ] || [ -z "${TOR_NICKNAME}" ]; then
            # if user did not change the default Nickname, genetrate a random pronounceable one
            RPW=$(pwgen -0A 8)
            TOR_NICKNAME="Tor4${RPW}"
            echo "Setting random Nickname: ${TOR_NICKNAME}"
        else
            echo "Setting chosen Nickname: ${TOR_NICKNAME}"
        fi
        printf "\nNickname %s\n" "${TOR_NICKNAME}" >> /etc/tor/torrc
    fi

    # Add Contact_Email from env variable, if none has been set in torrc
    if ! grep -q '^ContactInfo ' /etc/tor/torrc; then
        # if CONTACT_EMAIL is not null
        if [ -n "${CONTACT_EMAIL}" ]; then
            echo "Setting Contact Email: ${CONTACT_EMAIL}"
            printf "\nContactInfo %s\n" "${CONTACT_EMAIL}" >> /etc/tor/torrc
        fi
    fi
fi

printf "\n========================================================\n"
# Display OS version, Tor version & torrc in log
printf "%s %s\n" "$(grep PRETTY_NAME /etc/os-release | awk -F '=' '{print $2}' | sed 's/\"//g')" "$(grep VERSION_ID /etc/os-release | awk -F '=' '{print $2}' | sed 's/\"//g')"
tor --version
lyrebird -version
cat /etc/tor/torrc
printf "\n========================================================\n"

# else default to run whatever the user wanted like "bash"
exec "$@"
